// Generated by github.com/steida/coffee2closure 0.1.12
goog.require('globeGeometry.Size');
suite('globeGeometry.Size', function() {
  var Size;
  Size = globeGeometry.Size;
  suite('constructor', function() {
    return test('should work', function() {
      var size;
      size = new Size(8, -2.5);
      assert.equal(size.getWidth(), 8);
      return assert.equal(size.getHeight(), -2.5);
    });
  });
  return suite('equals', function() {
    test('should work with same size', function() {
      var size;
      size = new Size(17, 22);
      return assert.isTrue(size.equals(size), "Size does equal itself");
    });
    return test('should not work with size in different zoom level', function() {
      var size, size2;
      size = new Size(17, 22);
      size2 = new Size(4, 3);
      assert.isFalse(size.equals(size2), "Size does not equal different size");
      return assert.isFalse(size2.equals(size), "Size does not equal different size");
    });
  });
});