// Generated by github.com/steida/coffee2closure 0.1.12
/**
  @fileoverview Useful math methods
 */
goog.provide('globeGeometry.math');
goog.require('goog.math');
globeGeometry.math = function() {}

/**
  @param {number} num
  @param {number=} precision
  @return {number}
  @public
 */
globeGeometry.math.toFixed = function(num, precision) {
  var big, zeros;
  if (precision == null) {
    precision = 6;
  }
  zeros = Math.pow(10, precision);
  big = Math.abs(num) * zeros;
  return goog.math.sign(num) * goog.math.safeFloor(big) / zeros;
};

/**
  @param {number} num
  @param {number=} precision
  @return {number}
  @public
 */
globeGeometry.math.round = function(num, precision) {
  var pow;
  if (precision == null) {
    precision = 0;
  }
  if (precision === 0) {
    return Math.round(num);
  }
  pow = Math.pow(10, precision);
  return Math.round(num * pow) / pow;
};