// Generated by github.com/steida/coffee2closure 0.1.12
/**
  @fileoverview 2D point. Defined by x a y coordinate.
 */
goog.provide('globeGeometry.Point');
goog.require('globeGeometry.math');

/**
  @param {number} x
  @param {number} y
  @constructor
  @final
  @export
 */
globeGeometry.Point = function(x, y) {
  this.x = Number(x);
  this.y = Number(y);
}

/**
  @return {number}
  @export
 */
globeGeometry.Point.prototype.getX = function() {
  return this.x;
};

/**
  @return {number}
  @export
 */
globeGeometry.Point.prototype.getY = function() {
  return this.y;
};

/**
  @param {globeGeometry.Point} point
  @return {boolean}
  @export
 */
globeGeometry.Point.prototype.equals = function(point) {
  return this.x === point.getX() && this.y === point.getY();
};