// Generated by github.com/steida/coffee2closure 0.1.12
/**
  @fileoverview Tile in Mercator projection. Defined by x, y coordinate and zoom level
 */
goog.provide('globeGeometry.MercatorTile');
goog.require('globeGeometry.math');

/**
  @param {number} x
  @param {number} y
  @param {number} z
  @constructor
  @final
  @export
 */
globeGeometry.MercatorTile = function(x, y, z) {
  var max;
  x = Math.round(Math.abs(Number(x)));
  y = Math.round(Math.abs(Number(y)));
  this.z = Math.round(Math.abs(Number(z)));
  max = Math.pow(2, this.z) - 1;
  this.x = goog.math.clamp(x, 0, max);
  this.y = goog.math.clamp(y, 0, max);
}

/**
  @return {number}
  @export
 */
globeGeometry.MercatorTile.prototype.getX = function() {
  return this.x;
};

/**
  @return {number}
  @export
 */
globeGeometry.MercatorTile.prototype.getY = function() {
  return this.y;
};

/**
  @return {number}
  @export
 */
globeGeometry.MercatorTile.prototype.getZ = function() {
  return this.z;
};

/**
  @param {globeGeometry.MercatorTile} tile
  @return {boolean}
  @export
 */
globeGeometry.MercatorTile.prototype.equals = function(tile) {
  return this.x === tile.getX() && this.y === tile.getY() && this.z === tile.getZ();
};