// Generated by github.com/steida/coffee2closure 0.1.12
goog.require('globeGeometry.MercatorTile');
suite('globeGeometry.MercatorTile', function() {
  var Tile;
  Tile = globeGeometry.MercatorTile;
  suite('constructor', function() {
    return test('should clamp input', function() {
      var tile;
      tile = new Tile(10, 10, -3);
      assert.equal(tile.getX(), 7);
      assert.equal(tile.getY(), 7);
      return assert.equal(tile.getZ(), 3);
    });
  });
  return suite('equals', function() {
    test('should work with same tile', function() {
      var tile;
      tile = new Tile(17, 22, 5);
      return assert.isTrue(tile.equals(tile), "Tile does equal itself");
    });
    return test('should not work with tile in different zoom level', function() {
      var tile, tile2;
      tile = new Tile(17, 22, 5);
      tile2 = new Tile(4, 3, 3);
      assert.isFalse(tile.equals(tile2), "Tile does not equal different tile");
      return assert.isFalse(tile2.equals(tile), "Tile does not equal different tile");
    });
  });
});